name: Build

on:
  pull_request:
    branches: [ 2.X ]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 5.0.x

      - name: Checkout SharpHoundCommon
        uses: actions/checkout@v6
        with:
          repository: SpecterOps/SharpHoundCommon
          ref: v4
          path: SharpHoundCommon

      - name: Restore SharpHoundCommon Dependencies
        working-directory: SharpHoundCommon
        run: dotnet restore

      - name: Build SharpHoundCommon
        working-directory: SharpHoundCommon
        run: dotnet build --no-restore

      - name: Checkout SharpHound
        uses: actions/checkout@v6
        with:
          path: SharpHound

      - name: Restore SharpHound Dependencies
        working-directory: SharpHound
        run: dotnet restore

      - name: Build SharpHound
        working-directory: SharpHound
        run: dotnet build --no-restore