name: Build

on:
  pull_request:
    branches: [ 2.X ]
    types: [opened, synchronize]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash

    strategy:
      matrix:
        release:
          - type: Debug
          - type: Release

    name: Build (${{ matrix.release.type }})

    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.x

      - name: Checkout SharpHoundCommon
        uses: actions/checkout@v4
        with:
          repository: SpecterOps/SharpHoundCommon
          ref: v4
          path: SharpHoundCommon

      - name: Build SharpHoundCommon
        working-directory: SharpHoundCommon
        run: dotnet build -c ${{ matrix.release.type }}

      - name: Checkout SharpHound
        uses: actions/checkout@v4
        with:
          path: SharpHound

      - name: Build SharpHound
        working-directory: SharpHound
        run: dotnet build -c ${{ matrix.release.type }} -p:Version=0.0.0-rolling+${{ github.sha }}